# Generated by Django 2.1.4 on 2018-12-04 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('share_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('sell_date', models.DateField(blank=True, default=None, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Investments',
            },
        ),
    ]
